# Generated by Django 3.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=64)),
                ('ref_type', models.CharField(max_length=24)),
                ('dataset', models.CharField(max_length=24)),
                ('body', models.JSONField(verbose_name='body')),
            ],
            options={
                'db_table': 'api_ref_data',
            },
        ),
        migrations.AddConstraint(
            model_name='refdata',
            constraint=models.UniqueConstraint(fields=('ref_id', 'dataset'), name='unique_dataset_id'),
        ),
    ]
