# Generated by Django 4.0.2 on 2022-02-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xml2rfcItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subpath', models.CharField(db_index=True, max_length=255)),
                ('xml_repr', models.TextField()),
            ],
        ),
    ]
