# Generated by Django 4.0.2 on 2022-02-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml2rfc_compat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPathMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml2rfc_subpath', models.CharField(db_index=True, max_length=255)),
                ('query', models.TextField()),
                ('query_format', models.CharField(choices=[('json_struct', 'JSON containment'), ('docid_regex', 'docid substring'), ('json_path', 'JSON path'), ('websearch', 'web search')], max_length=50)),
            ],
        ),
    ]
