# Generated by Django 4.0.2 on 2022-02-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml2rfc_compat', '0002_manualpathmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpathmap',
            name='docid',
            field=models.CharField(db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
