# Generated by Django 3.2.9 on 2021-11-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(help_text='Reference (or ID). Corresponds to source dataset filename without extension.', max_length=128)),
                ('ref_id', models.CharField(max_length=64)),
                ('ref_type', models.CharField(max_length=24)),
                ('dataset', models.CharField(help_text='Internal dataset ID.', max_length=24)),
                ('body', models.JSONField()),
                ('representations', models.JSONField()),
            ],
            options={
                'db_table': 'api_ref_data',
                'unique_together': {('ref', 'dataset')},
            },
        ),
    ]
