# Generated by Django 3.2.11 on 2022-01-09 12:28

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='refdata',
            index=django.contrib.postgres.indexes.GinIndex(fields=['body'], name='body_gin'),
        ),
    ]
