# Generated by Django 3.2.11 on 2022-01-09 12:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_refdata_body_gin'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='refdata',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector(django.db.models.functions.comparison.Cast('body', models.TextField()), config='english'), name='body_astext_gin'),
        ),
    ]
