# Generated by Django 3.2.11 on 2022-01-09 12:55

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_refdata_body_astext_gin'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='refdata',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('body', config='english'), name='body_ts_gin'),
        ),
    ]
