# Generated by Django 3.2.11 on 2022-01-11 15:41

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations
import django.db.models.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_refdata_body_ts_gin'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='refdata',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector(django.db.models.fields.json.KeyTransform('docid', 'body'), config='english'), name='body_docid_gin'),
        ),
    ]
