# Generated by Django 4.0.1 on 2022-01-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_refdata_body_docid_gin'),
    ]

    operations = [
        migrations.RunSQL('''
            CREATE INDEX "body_json_ts_gin" ON "api_ref_data"
            USING gin (to_tsvector('english'::regconfig, body));
        '''),
    ]
