# Generated by Django 4.0.5 on 2022-06-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceIndexationOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(db_index=True, max_length=250)),
                ('task_id', models.CharField(db_index=True, max_length=250, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('successful', models.BooleanField(default=False)),
                ('notes', models.TextField(default='')),
            ],
        ),
    ]
